### ISSUE TITLE
Tune timings

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Offbot_Code#117]
```[tasklist]
### Tasks
- [ ] Intaking doesn't need to pivot all the time
- [ ] Shooting in auto (maybe slowdown)
- [x] Pivoting with elevator can be optimized
- [ ] Auto drive train speed
```
