### ISSUE TITLE
Write some LED code ✨

### ISSUE THREAD

**Issue by AlenaNguyen** [FRCTeam3255/2024_Offbot_Code#47]
LED = State

```[tasklist]
### Tasks
- [ ] Game piece in robot (INTAKING - beam break)
- [x] Game piece collected (STORE_FEEDER)
- [x] Amp mode (PREP_AMP)
- [x] Backwards Sub (PREP_BACKWARDS_SUB)
- [x] Front Sub (PREP_SUB)
- [x] Vision mode (PREP_VISION)
- [ ] #114
```

**Comment by TaylerUva** [comment]
LED = STATE

**Comment by TaylerUva** [comment]
@Alenguye582 ✨✨✨✨✨
