### ISSUE TITLE
Create Autos

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Offbot_Code#48]
```[tasklist]
### Tasks
- [ ] https://github.com/FRCTeam3255/2024_Offbot_Code/issues/55
- [ ] https://github.com/FRCTeam3255/2024_Offbot_Code/issues/54
- [ ] https://github.com/FRCTeam3255/2024_Offbot_Code/issues/56
- [ ] https://github.com/FRCTeam3255/2024_Offbot_Code/issues/103
- [ ] https://github.com/FRCTeam3255/2024_Offbot_Code/issues/104
```

**Comment by TaylerUva** [comment]
@ACat701 and @Alenguye582 we can discuss more in the room or in this issue thread.

For now I added what our last bot had. We will convert them to individual issues (and rank them seperately) once we confirm what we want. Hopefully this will be easier with the state machine 🤞

**Comment by TaylerUva** [comment]
Test from button
