### ISSUE TITLE
Feasibility Testing

### ISSUE THREAD

**Issue by TaylerUva** [FRCTeam3255/2024_Offbot_Code#58]
```[tasklist]
### Tasks
- [ ] https://github.com/FRCTeam3255/2024_Offbot_Code/issues/71
- [x] Test 3 Sub shots
- [x] Test 3 Spikes shots
- [x] Test 3 Wings shots
- [x] Test 3 Amp shots without elevator
- [ ] https://github.com/FRCTeam3255/2024_Offbot_Code/issues/66
- [ ] https://github.com/FRCTeam3255/2024_Offbot_Code/issues/67
- [ ] https://github.com/FRCTeam3255/2024_Offbot_Code/issues/68
- [ ] https://github.com/FRCTeam3255/2024_Offbot_Code/issues/69
- [ ] https://github.com/FRCTeam3255/2024_Offbot_Code/issues/70
```
